# https://lightning.ai/docs/pytorch/stable/api/pytorch_lightning.callbacks.RichModelSummary.html

model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: 1 # the maximum depth of layer nesting that the summary will include
